### PR TITLE
parametrize dockerfile pipeline: docker image reference and git uri

### PR DESCRIPTION
**Pull request by o-orand**
move default values to public-config.yml

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
@o-orand Thanks for the pull request, could you please rebase off develop? Thanks!

**Comment by o-orand** [comment]
No problem, I going to rebase.

**Comment by o-orand** [comment]
@RochesterinNYC done. Thanks for merging all my PRs.

**Comment by RochesterinNYC** [comment]
Thanks!

**Pull request merged**
