### PR TITLE
parametrize github-release org and create a "public" credential file

### PR DESCRIPTION
**Pull request by o-orand**
replace `type: github-release | source: | user: cloudfoundry` with `type: github-release | source: | user: {{buildpacks-github-org}}`. Also introduce a placeholder for public credentials (initialized with this new one only)

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
@o-orand How is the `public-credentials.yml` file used? I don't see this new file being utilized anywhere.

**Comment by o-orand** [comment]
@RochesterinNYC, it is not used yet. The idea behind was to add a placeholder for credentials which are moved to concourse credentials. I was thinking, the creation of this list as first step. And after use it in update script. Maybe I should have create a separate PR to discuss this.

**Comment by o-orand** [comment]
Update, now it's used :smile: and it should work.

**Comment by sesmith177** [comment]
Hello @o-orand, this looks mostly good. The `public-credentials.yml` file should be renamed as it contains config, not credentials. Also,  this [line](https://github.com/cloudfoundry/buildpacks-ci/pull/8/commits/4c016e52f765ede4ba69bfc8de00bf5722b37aeb#diff-f1fa6f461f51a128080fcc9308c46d09R22) should probably use the whole filename.

Once this is done, we'll merge

**Comment by RochesterinNYC** [comment]
Hey @o-orand, any update on this small change to the name of the public config file?

**Comment by o-orand** [comment]
Hello @sesmith177 and @RochesterinNYC, sorry I was on vacations :smile:. I've updated the PR. Thanks for comments.

**Comment by RochesterinNYC** [comment]
@o-orand thanks for the update!

**Pull request merged**
