### PR TITLE
bump-php-modules script/README: add info from story

### PR DESCRIPTION
**Pull request by arjun024**
See an example story https://www.pivotaltracker.com/n/projects/2537714/stories/184102817

### CODE REVIEW

**Comment by arjun024** [comment]
@thitch97

**Comment by brayanhenao** [comment]
@arjun024 Note that in #223 we refactor the directory in which the PHP Extensions files are located. Does this affect something else?

**Comment by arjun024** [comment]
@brayanhenao I don't believe so

**Comment by brayanhenao** [comment]
Then update this README. Replace:

`tasks/build-binary-new[-cflinuxfs4]/php8-base-extensions.yml`

with

`tasks/build-binary-new[-cflinuxfs4]/php_extensions/php8-base-extensions.yml`


Ref: https://github.com/cloudfoundry/buildpacks-ci/tree/master/tasks/build-binary-new-cflinuxfs4/php_extensions

**Comment by arjun024** [comment]
@brayanhenao Good catch. Done

**Review by sophiewigmore — APPROVED** [review]

**Pull request merged**
