### PR TITLE
rename the test pipeline for cflinuxfs4 to avoid any confusion

### PR DESCRIPTION
**Pull request by arjun024**
This is a pipeline engineers can use to test dependencies and does not build the dependencies that go into the buildpack.

Also remove variables not used

### CODE REVIEW

**Comment by arjun024** [comment]
@brayanhenao @sophiewigmore @robdimsdale

This is just a suggestion as the pipeline name `dependency-builds-cflinuxfs4` could confuse people to believe that production dependencies are built in this separate pipeline. Any thoughts?

If merged, after-merge actions:
[ ] Fly the pipeline and test with one of the already passed dependency
[ ] Destroy old pipeline
[ ] Update the wiki

**Review by robdimsdale — APPROVED** [review]
Yup, I found it confusing when i first looked at it. I think this name is better.

**Comment by arjun024** [comment]
Running the new pipeline here to make sure it works the same: https://buildpacks.ci.cf-app.com/teams/main/pipelines/test-bed-dependency-builds-fs4

**Review by brayanhenao — APPROVED** [review]

**Comment by arjun024** [comment]
All post merge tasks done

**Pull request merged**
